attempt to inherit the file type/provider
This doesn't work because boom.

    Debug: Reloading windows file provider
    Error: Could not autoload puppet/provider/datacat/datacat: constant Puppet::Type::Datacat::ProviderWindows not defined
    Error: Could not autoload puppet/type/datacat: Could not autoload puppet/provider/datacat/datacat: constant Puppet::Type::Datacat::ProviderWindows not defined
    Error: Could not autoload puppet/type/datacat: Could not autoload puppet/provider/datacat/datacat: constant Puppet::Type::Datacat::ProviderWindows not defined on node jay.surfnet.iacbox
    Error: Could not autoload puppet/type/datacat: Could not autoload puppet/provider/datacat/datacat: constant Puppet::Type::Datacat::ProviderWindows not defined on node jay.surfnet.iacbox